# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rodrigo Lallana
title: Ingeniero software
email: rj.lallana@gmail.com
website: www.github.com/rjlallana
additional_info:
phone_number: 649596301
city: Madrid

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: godrik
github_username:  rjlallana
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: rodrigolallana
linkedin_username: rodrigo-lallana
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: 649596301
# - title: Madrid
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "G-ZRHHJ0758N"

# About Section
about_title: Sobre mi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Tengo 23 años, soy un estudiante de Ingeniería de Software en la Universidad Politécnica de Madrid. Tengo todas las asignaturas superadas, a falta de realizar las prácticas externas y terminar el proyecto de fin de grado. Mi intención es incorporarme al mundo laboral una vez obtenido el título y plantearme realizar un master compaginandolo con el trabajo.

  En 2020 fui de Erasmus a la universidad Tecnológica de Tallin 6 meses donde entre otras asignaturas curse una asignatura de máster sobre Machine Learning.  Me considero una persona abierta, tolerante, proactiva, detallista, con capacidad autodidacta y con mucha motivación para aprender y desarrollarme a nivel profesional.

content:
  - title: Aptitudes # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      ## Programacion
      * Nivel intermedio de Python, Java, C/C++, C#, JavaScript, Kotlin, Matlab
      * Experiencia con Python usando librerías como Numpy, Pandas, TensorFlow y Pytorch
      * Experiencia con Java y Spring Boot para crear APIs REST
      * Experiencia con programación orientada a objetos, estructuras de datos, algoritmos de ordenación, concurrencia y análisis de algoritmos y su complejidad.
      * Conocimiento de desarrollo web (Bootstrap, React, VUE) y desarrollo Android

      ## Desarrollo Software
      * Conocimiento sobre metodologías de desarrollo software y su ciclo de vida
      * Experiencia con la metodología de desarrollo ágil Scrum y con la metodología DevOps
      * Experiencia con Linux, bash y Git/Github para control de versiones
      * Conocimiento sobre calidad del software y técnicas de testing

      ## Machine Learning
      * Conocimiento de los fundamentos matemáticos de Machine Learning.
      * Experiencia con algoritmos de aprendizaje supervisado y no supervisado.
      * Experiencia con Deep Learning y el uso de diferentes tipo de redes de neuronas

      ## Base de Datos
      * Nivel intermedio de SQL(MySQL) 
      * Experiencia con modelaje y optimización de acceso a base de datos relacionales.
      * Experiencia con modelos de datos semiestructurados como XML y de modelos de datos NoSQL como MongoDB

      ## Idiomas
      * Fluidez para comunicarme en Inglés tanto de forma oral como escrita
      * Nivel C1 de Inglés en 2020, OLS (Prueba de Nivel de la UE para estancias Erasmus)
      * Nivel B2 de Inglés en 2015, Cambridge First Certificate

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Telefonica
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Ingeniero DevOps Junior
        caption: Mayo 2021 - Presente
        quote: >
          Beca Telentum
        description: | # this will include new lines to allow paragraphs
            * Automatización y orquestación de la infraestructura y funcionalidad de diferentes servicios usando Ansible, Python y Bash.
            * Monitoreo de los servicios usando Splunk y AWX.
            * Orquestación de contenedores (Kubernetes) y servicios cloud (AWS)
            * Metodología ágil y planificación usando Jira.

  - title: Formación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Universidad Tecnológica de Tallin (TalTech) 
        caption: 2020
        sub_title: Estancia Erasmus
        # description: | # this will include new lines to allow paragraphs

      - layout: top-middle
        title: Universidad Politécnica de Madrid 
        sub_title: Grado de Ingeniería del Software
        # description: | # this will include new lines to allow paragraphs

  - title: Un poco mas sobre mi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Aparte de mi interes en todo el mundo tecnologico, otros intereses y hobbies que tengo son:
      - Viajar
      - Videojuegos
      - Escalada y montañismo
      - Gimnasia
      - Construir drones
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
